/mission_controller_node:
  ros__parameters:
    allow_speed_tuning: true
    alternate_min_area_px: 250
    avoid_hold_s: 2.0
    avoid_speed: 80
    bev_pad: 250
    bev_top_shift: -15
    car_center_x: 325.0
    car_center_y: 179.0
    center_ema_alpha: 0.35
    cmd_topic: /dry_run/topic_control_signal
    confidence: 0.5
    debug_log: false
    debug_log_interval: 10
    debug_topic: /mission/debug_image
    device: cuda:0
    ema_alpha: 0.6
    green_confirm_frames: 3
    green_h_max: 90
    green_h_min: 40
    heading_gain: 0.55
    heading_step: 3
    hsv_s_min: 100
    hsv_v_min: 95
    image_reliability: reliable
    image_timeout_s: 0.75
    image_topic: /mission/image_raw
    loaded_tuning_config: /home/autolab/.config/autodrive/mission_tuning.yaml
    look_shift: 0
    lookahead_index: 30
    max_center_jump_px: 80.0
    max_missed_frames: 12
    max_steering: 7.0
    max_steering_angle: 50.0
    min_component_area: 250
    model_path: /home/autolab/autodrive_ws/Autonomous_Capstone-integrated/install/skku_track_drive_pkg/share/skku_track_drive_pkg/models/mission/best.pt
    obstacle_clear_frames: 5
    obstacle_confirm_frames: 3
    obstacle_near_y: 300
    path_margin_px: 35
    profile: false
    profile_input_fps: 0.0
    profile_report_interval: 50
    profile_warmup_frames: 10
    publish_analysis: true
    publish_bev_debug: true
    publish_debug: true
    red_confirm_frames: 3
    red_h_high_min: 160
    red_h_low_max: 10
    roi_cut: 300
    speed: 80
    stanley_gain: 0.027
    stanley_softening: 0.001
    start_enabled: true
    steering_sign: 1.0
    traffic_min_bottom_y: 80
    traffic_min_color_ratio: 0.02
    traffic_min_width: 20
    use_sim_time: false
    virtual_lane_width: 290
    wait_for_green: 0
    yellow_h_max: 30
    yellow_h_min: 20
    yellow_speed: 60

