<?xml version="1.0"?>
<package format="3">
  <name>sensor_bringup_pkg</name><version>0.1.0</version>
  <description>SKKU camera/RPLidar bringup</description>
  <maintainer email="noreply@example.com">skku</maintainer><license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend><depend>sensor_msgs</depend><depend>geometry_msgs</depend>
  <depend>cv_bridge</depend><depend>tf2_ros</depend><exec_depend>python3-serial</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
